### PR TITLE
[tvos] Support building for tvos

### PR DESCRIPTION
**Pull request by fuzzard**
Adds build support for tvos platform

Upstream PR for actual build fix (merged)

https://github.com/libretro/mrboom-libretro/pull/10

### CODE REVIEW

**Comment by garbear** [comment]
Same comment as https://github.com/kodi-game/game.libretro.2048/pull/11, can you PR the change to https://github.com/kodi-game/kodi-game-scripting/?

**Comment by fuzzard** [comment]
Do you want this PR closed and just do the scripting one?
Have a patch we need to carry now. Missing arch type issues when using xcode and not defining CC/CXX. strangely building from make -C tools/depends/binary-addons works without it.

**Comment by garbear** [comment]
Keep it open for the patch. The CMakeLists.txt change will drop out when we rebase on the kodi-game-scripting update.

**Comment by fuzzard** [comment]
PR'd patch upstream

https://github.com/libretro/mrboom-libretro/pull/10

**Comment by fuzzard** [comment]
dropped Cmake change, as its been upstreamed to kodi-game-scripting. Upstream build fixes have been merged, so updated the zip location.

Good for merge

**Pull request closed without merging**
