### PR TITLE
Update mrboom.txt

### PR DESCRIPTION
**Pull request by frranck**

### CODE REVIEW

**Comment by garbear** [comment]
Thanks for the contribution! Before we merge, do settings or language files need to be updated?

**Comment by frranck** [comment]
Actually yes, autofire has to be removed
  
https://github.com/kodi-game/game.libretro.mrboom/blob/master/game.libretro.mrboom/resources/settings.xml#L5

then we could add

```
static const struct retro_variable var_mrboom_musicvolume = { "mrboom-musicvolume", "Music volume; 100|0|5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95" };
static const struct retro_variable var_mrboom_sfxvolume   = { "mrboom-sfxvolume", "Sfx volume; 50|55|60|65|70|75|80|85|90|95|100|0|5|10|15|20|25|30|35|40|45" };
```

**Comment by garbear** [comment]
We automate our generation of settings and strings with https://github.com/kodi-game/kodi-game-scripting because there's over 100 cores. It would be idea if we could point the script at the working commit and have the fluff generated automatically.

**Comment by frranck** [comment]
Could you please run the script for the options? the tar.gz is pointing to 454d6141431571e9bc784d5d4cbc728534066f4b, but you could use master as well because they haven't change.

**Comment by eigendude** [comment]
I'll run the script when I get a chance. It's likely that your repo will be set as the upstream and it'll build from git, this PR won't be needed.

**Comment by garbear** [comment]
I'll run the script when I get a chance. It's likely that your repo will be set as the upstream and it'll build from git, this PR won't be needed.

**Comment by frranck** [comment]
Not sure, the problem is the missing submodules/files in the release version, so I created a complete version.

**Comment by garbear** [comment]
Oh right, then we can rebase this PR once the script runs

**Comment by frranck** [comment]
Any update on that one?

**Comment by eigendude** [comment]
@frranck I ran the script on 5.2 and all the strings got removed: https://github.com/kodi-game/game.libretro.mrboom/commit/d6b7515

Was mrboom switched over to the new settings API?

**Comment by garbear** [comment]
@frranck I ran the script on 5.2 and all the strings got removed: https://github.com/kodi-game/game.libretro.mrboom/commit/d6b7515

Was mrboom switched over to the new settings API?

**Comment by frranck** [comment]
I'm not sure what is the new settings API, but this is where the settings are defined:

https://github.com/Javanaise/mrboom-libretro/blob/e4bec7e0962e4ba1fd8be5bfdcc1683647ef0349/libretro/retro.cpp#L44

**Comment by garbear** [comment]
Thanks for linking, that is the old API so something is probably broken in the maintenance script. I'll see if I can track it down

**Comment by garbear** [comment]
I updated the dependency URL, but the settings and language files didn't come back. It seems that everything is working except the RETRO_ENVIRONMENT_SET_VARIABLES call. Do you know why this would be failing?

**Comment by frranck** [comment]
We changed the directory from the retro.cpp file, it used to be in the root one and now it's in libretro.
Could it be your script is not going there?

>except the RETRO_ENVIRONMENT_SET_VARIABLES call

So you're not only parsing the retro_variable instantiation lines?

**Comment by garbear** [comment]
We're not parsing the source, we compile the core and load the .so with ctypes. We call `retro_init()` and parse the variables struct using ctypes. That's where the settings and language file should be coming from. It worked in older versions of DOSBox, not sure why ctypes is reporting an empty variables struct.

**Comment by frranck** [comment]
Could it be because they're static?

**Comment by garbear** [comment]
I never figured out the settings problem with kodi-game-scripting, but fortunately I wrote a backup settings generator in C++ inside of game.libretro. I ran `MrBoom-src-5.2.454d614.tar.gz` and it generated these files: https://github.com/kodi-game/game.libretro.mrboom/commit/a9b36420c92b3dd69b2c786655a56a76fdca6658

I cherry-picked this commit and tagged new versions. They should be running through CI now.

CI runs are here: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-game%2Fgame.libretro.mrboom/activity

Windows is failing sporadically due to expired certs on some of our mirrors. iOS aarch64 fails with this error:

```

ld: warning: ld: warning: ignoring file /Applications/Xcode10.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (arm64): /Applications/Xcode10.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/lib/libSystem.tbd
ignoring file /Applications/Xcode10.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/lib/libm.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (arm64): /Applications/Xcode10.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/lib/libm.tbd
ld: warning: ignoring file /Applications/Xcode10.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/lib/libc++.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (arm64): /Applications/Xcode10.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/lib/libc++.tbd
Undefined symbols for architecture arm64:
...
_vsprintf", referenced from:
      _log_error in mrboom_data.o
      _log_info in mrboom_data.o
  "_wcstombs", referenced from:
      _utf16_to_utf8_string_alloc in encoding_utf.o
  "_write", referenced from:
      _retro_vfs_file_write_impl in vfs_implementation.o
     (maybe you meant: _filestream_write_file, _retro_vfs_file_write_impl , _filestream_write , _memstream_write , _config_file_write )
ld: symbol(s) not found for architecture arm64
```

**Comment by garbear** [comment]
@frranck I was testing on Windows, and I updated my repos in kodi today, and the new version showed up. Can you refresh your repos and give it a try?

**Comment by frranck** [comment]
@garbear nice ! not sure how to test it from sources, but if its fine on windows there should be no issue.

**Comment by garbear** [comment]
OK then I'll close this after cherry-picking manually. Let me know if any issues turn up!

**Pull request closed without merging**
