### PR TITLE
Remove platform from add-on name

### PR DESCRIPTION
**Pull request by garbear**
We probably shouldn't have "bomberman" appear on the homescreen the user first sees. This should be done by kodi-game-scripting, but for now I'm hardcoding the removal here.

### CODE REVIEW

**Comment by garbear** [comment]
@fetzerch

**Comment by fetzerch** [comment]
Currently we get the `display_name` from libretro-super: https://github.com/libretro/libretro-super/blob/master/dist/info/mrboom_libretro.info#L1.
Do you want to change this for all addons? Cause they also refer to for example 'Nintendo - SNES / Famicom'. If it's something special for just one (or a few) addons, we'll have to make it configurable.

**Comment by garbear** [comment]
I don't know where to draw the line. We took all the logos off the controllers, but I don't know how antagonistic game publishers will be.

**Comment by garbear** [comment]
I think there's value in having the *platform* in the name, because there's no confusion, but in this case it we have the *game* in the name and it could possibly look like we're trying to pass off our clone as the original game.

**Pull request closed without merging**
