### PR TITLE
[PR 16039] ios Darwin_embedded build change

### PR DESCRIPTION
**Pull request by fuzzard**
https://github.com/xbmc/xbmc/pull/16039

Merge if/when the above PR is merged into kodi master

### CODE REVIEW

**Comment by garbear** [comment]
Can you submit to kodi-game-scripting? https://github.com/fetzerch/kodi-game-scripting/blob/master/templates/addon/depends/common/%7B%7B%20game.name%20%7D%7D/CMakeLists.txt.j2#L26

thanks

**Comment by fuzzard** [comment]
Yeah sure, will do

**Comment by fuzzard** [comment]
Done as requested.

**Review by Rechi — COMMENTED** [review]
This will break building the add-on for Leia as `CORE_SYSTEM_NAME` is still ios for Leia.

**Comment by phunkyfish** [comment]
This failed on loading the ming tarball, could someone kick off another build?

**Comment by hudokkow** [comment]
jenkins is happy!

**Comment by phunkyfish** [comment]
Nice, thanks!

**Pull request merged**
